# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-03 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thing',
            new_name='Panels',
        ),
    ]
