# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-03 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20161203_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panels',
            new_name='Panel',
        ),
    ]
